version: '3'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=MarDemonic
     - MYSQL_PASSWORD=MarDemonic
     - MYSQL_DATABASE=DB_server
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
     - mysql
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1 
    ports:
      - 8081:80
  
  crud:
    build: .
    container_name: crud
    restart: always
    depends_on:
      - mysql
      - phpmyadmin
    ports:
      - 8080:80
    volumes:
      - ./front/crud /usr/share/nginx/html/